services:
  app:
    container_name: webapi-app
    build:
      context: ../backend
      dockerfile: Dockerfile.multistage
    env_file:
      - .app.env
    networks:
      - app-network
    ports:
      - "5555:80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: webapi-postgres
    image: postgres:17-alpine
    env_file:
      - .postgres.env
    ports:
      - "5454:5432"
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pg_data:
